spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  mail:
    password: pkskpvffkcvmgesb
    port: 1025
    username: craftsy@gmail.com
    host: localhost
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  jpa:
    hibernate:
      ddl-auto: none
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true

application:
  security:
    cookie:
      secure: false
      expiration: 1800000
    token:
      secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
      expiration: 1800000
      refresh:
        expiration: 7200000
  url:
    token:
      expiration: 1440
    baseUrl: http://localhost:8080